### ISSUE TITLE
bad argument error

### ISSUE THREAD

**Issue by ussjonas** [aaronk6/ERC20-MoneyMoney#1]
Hi I have tried to use your plugin, but I got this:

ERC20.lua:141: bad argument #1 to 'match' (string expected, got nil)

Best

**Comment by aaronk6** [comment]
Hi, I also saw this and fixed it here: 092d827c2061b496acbd793b1d476e77bdea9474

However, since yesterday there’s another error that causes an empty account. I’ll look into this.

**Comment by aaronk6** [comment]
f87e25fe63c1e4593303a097007d9117d60d10f1 fixes both issues. Signed version is one the way.
