### ISSUE TITLE
Importing ERC20 tokens no longer works

### ISSUE THREAD

**Issue by philipgunther** [aaronk6/ERC20-MoneyMoney#3]
The Etherscan website seems to have changed, so the script can no longer read account balances.

Otherwise, a great extension :)

**Comment by aaronk6** [comment]
Thank you! Check out the latest update—I’ve already migrated to Ethplorer (note that this needs the latest Beta version MoneyMoney because Ethplorer is not white-listed yet).

https://github.com/aaronk6/ERC20-MoneyMoney/releases/tag/v1.04

**Comment by philipgunther** [comment]
Thank you very much! It works again :)
