### ISSUE TITLE
ERC20.lua:89: attempt to concatenate field 'symbol' (a nil value)

### ISSUE THREAD

**Issue by cryptochrome** [aaronk6/ERC20-MoneyMoney#4]
Hi,

I am getting this error message for a couple of weeks now everytime I try to add a new ETH address to MoneyMoney or when I try to update existing accounts:

ERC20.lua:89: attempt to concatenate field 'symbol' (a nil value)

**Comment by aaronk6** [comment]
Hi,

Thanks for the report! I can’t reproduce the issue here, but I think https://github.com/aaronk6/ERC20-MoneyMoney/commit/17829b59b20fe5830896937d81a5b2bb82a3349f will fix it. I’ve submitted a new version to MoneyMoney. So a signed version for you to try will be available soon.

**Comment by aaronk6** [comment]
@cryptochrome Would you mind trying the latest release (https://github.com/aaronk6/ERC20-MoneyMoney/releases/tag/v1.05) and let me know if this fixes the error message?

**Comment by cryptochrome** [comment]
> @cryptochrome Would you mind trying the latest release (https://github.com/aaronk6/ERC20-MoneyMoney/releases/tag/v1.05) and let me know if this fixes the error message?

Just tried it, works like a champ. No more error messages :)  Thanks for fixing it!
