### ISSUE TITLE
ERC20.lua:123: attempt to call a nil value (field 'pow')

### ISSUE THREAD

**Issue by caratage** [aaronk6/ERC20-MoneyMoney#5]
After this extension has worked flawlessly for a long time, I now get this error upon updating the ERC20 account in MoneyMoney: `ERC20.lua:123: attempt to call a nil value (field 'pow')`

**Comment by thomasdingler** [comment]
Same problem on my side. Started with Moneymoney 2.4.44 iirc.

**Comment by maxschoenberger** [comment]
It's a LUA issue. You can replace `math.pow(10, decimals)` in line 123 with `10^decimals` and it'll work again.

**Comment by caratage** [comment]
Unfortunately not. I changed the line as suggested but then, the whole extension seems to stop working. 

1. Updating the ERC20 accounts will produce this error: "Für diese Bank ist keine Web-Scraping-Unterstützung vorhanden."
2. The extension is no longer showing in the list when creating a new account.

With the version `math.pow(10, decimals)` on line 123, I can add a new ERC20 account:

![account can be added](https://github.com/user-attachments/assets/58748466-7f07-469c-8c10-75412ee4adf9)

But with `10^decimals` on line 123, the extension is no longer showing:

![adding not possible](https://github.com/user-attachments/assets/d4a3a7dd-3ceb-463a-86e5-f89bb8dbda2f)

Tested with MoneyMoney v2.4.44  and v2.4.45 Retail.

**Comment by maxschoenberger** [comment]
This probably happens because the signature (hash) of the extension is not correct anymore now that you edited it. You can disable the signature checking under settings -> extensions (can be a security risk, so proceed with caution).

**Comment by caratage** [comment]
Is there a way to update the signature after modification so that I don't have to disable the security check?

**Comment by maxschoenberger** [comment]
Only the MoneyMoney developer can generate it, so you‘ll have to submit a support ticket in this case.

**Comment by caratage** [comment]
Ok, thanks for clarifying. So as of now, the ERC20.lua extension is no longer working for users of MoneyMoney v2.4.44 and above. Maybe consider updating it or removing it from the MoneyMoney extensions?

**Comment by aaronk6** [comment]
I will submit an update to MoneyMoney.

**Comment by aaronk6** [comment]
The signed version is now available in the [Releases section](https://github.com/aaronk6/ERC20-MoneyMoney/releases) and at https://moneymoney-app.com/extensions/.

**Comment by caratage** [comment]
Thanks Aaron. Well appreciated!

**Comment by thomasdingler** [comment]
Great! Works like a charm again!
